<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateOmraNationalitiesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('omra_nationalities', function (Blueprint $table) {
            $table->increments('n_id')->unsigned();
            $table->string('n_nationality',50);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('omra_nationalities');
    }
}
//INSERT INTO omra_countries(c_country) VALUES('Albanian'),
//('Algerian'),
//('Andorran'),
//('Angolian'),
//('Antiguan'),
//('Argentinian'),
//('Armenian'),
//('Australian'),
//('Austrian'),
//('Azerbaijanese'),
//('Bahamian'),
//('Bahrainian'),
//('Bangladeshi'),
//('Barbadian'),
//('Belarusian'),
//('Belgian'),
//('Belizian'),
//('Benin'),
//('Bhutanian'),
//('Bolivian'),
//('Bosnian'),
//('Batswana'),
//('Brazilian'),
//('Bruneian'),
//('Bulgarian'),
//('Burkina-Fasoian'),
//('Burmian'),
//('Burundian'),
//('Cambodian'),
//('Cameroonian'),
//('Canadian'),
//('Cape Verdean'),
//('Central African'),
//('Chadian'),
//('Chilean'),
//('Chinese'),
//('Colombian'),
//('Comorian'),
//('Congolese'),
//('Costa Rican'),
//('Cote dIvoirean'),
//('Cretean'),
//('Croatian'),
//('Cuban'),
//('Cypriot'),
//('Czech'),
//('Danish'),
//('Djiboutian'),
//('Dominican'),
//('East-Timorese'),
//('Ecuadorian'),
//('Egyptian'),
//('El-Salvadorian'),
//('Equatorial-Guinean'),
//('Eritrean'),
//('Estonian'),
//('Ethiopian'),
//('Fijian'),
//('Finnish'),
//('French'),
//('Gabonese'),
//('Gambian'),
//('Georgian'),
//('German'),
//('Ghanian'),
//('Greek'),
//('Grenadian'),
//('Guadeloupian'),
//('Guatemalan'),
//('Guinean'),
//('Guinean Bissau'),
//('Guyanese'),
//('Haitian'),
//('Holy-Seean'),
//('Honduran'),
//('Hong Kongese'),
//('Hungarian'),
//('Icelander'),
//('Indian'),
//('Indonesian'),
//('Iranian'),
//('Iraqi'),
//('Irish'),
//('Israeli'),
//('Italian'),
//('Ivory Coast - Baoule'),
//('Jamaican'),
//('Japanese'),
//('Jordanian'),
//('Kazakh'),
//('Kenyan'),
//('Kiribati'),
//('Korean-North'),
//('Korean-South'),
//('Kosovan'),
//('Kuwaiti'),
//('Kyrgyz'),
//('Lao'),
//('Latvian'),
//('Lebanese'),
//('Mosotho'),
//('Liberian'),
//('Libyan'),
//('Liechtenstein'),
//('Lithuanian'),
//('Chinese - Macau'),
//('Macedonian'),
//('Malagasy'),
//('Malawian'),
//('Malaysian'),
//('Maldivian'),
//('Malian'),
//('Maltese'),
//('Marshallese'),
//('Mauritanian'),
//('Mauritanian'),
//('Mexican'),
//('Micronesian'),
//('Moldovian'),
//('Monacan'),
//('Mongolian'),
//('Montenegrin'),
//('Moroccan'),
//('Mozambican'),
//('Namibian'),
//('Nauruan'),
//('Nepali'),
//('Dutch'),
//('New Zealander'),
//('Nicaraguan'),
//('Nigerien'),
//('Nigerian'),
//('Norwegian'),
//('Omani'),
//('Pakistani'),
//('Palauan'),
//('Panamian'),
//('Papua New Guinean'),
//('Paraguayan'),
//('Peruvian'),
//('Filipino'),
//('Polish'),
//('Portugese'),
//('Qatari'),
//('Romanian'),
//('Russian'),
//('Rwandan'),
//('Saint Lucian'),
//('Saint Vincent and the Grenadian'),
//('Samoan'),
//('San Marino'),
//('Sao Tome and Principean'),
//('Saudi Arabian'),
//('Scottish'),
//('Senegalese'),
//('Serbian'),
//('Seychellois'),
//('Sierra Leone'),
//('Singaporean'),
//('Slovakian'),
//('Slovenian'),
//('Solomon Islander'),
//('Somalian'),
//('South African'),
//('Spanish'),
//('Sri Lankan'),
//('Sudanese'),
//('Suriname'),
//('Swazi'),
//('Swedish'),
//('Swiss'),
//('Syrian'),
//('Taiwanese'),
//('Tajik'),
//('Tanzanian'),
//('Thai'),
//('Tibetian'),
//('Timor-Leste'),
//('Togolese'),
//('Tongan'),
//('Tobagonian'),
//('Tunisian'),
//('Turkish'),
//('Turkmen'),
//('Tuvaluan'),
//('Ugandan'),
//('Ukrainian'),
//('Emirati'),
//('British'),
//('American'),
//('Uruguayan'),
//('Uzbek'),
//('Ni-Vanuatu'),
//('Venezuelan'),
//('Vietnamese'),
//('Yemeni'),
//('Zambian'),
//('Zimbabwean');